services:
  pgbouncer:
    image: rmccaffrey/pgbouncer:latest
    restart: unless-stopped
    container_name: 'pgbouncer'
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER_NAME:-resto}:${DATABASE_USER_PASSWORD:-resto}@restodb:5432/resto
      - POOL_MODE=transaction
      - MAX_DB_CONNECTIONS=100
      - DEFAULT_POOL_SIZE=40
      - AUTH_TYPE=scram-sha-256
    depends_on:
      - restodb
    networks:
      - default
      - external