#!/bin/bash
#
# Copyright 2018 Jérôme Gasperi
#
# Licensed under the Apache License, version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

PROJECT_NAME=resto

function showUsage {
    echo ""
    echo "   Undeploy resto based docker instance "
    echo ""
    echo "   Usage $0 <Project name>"
    echo ""
    echo "      -h | --help show this help"
    echo ""
    echo "      !!! This script requires docker and docker-compose !!!"
    echo ""
}

# Parsing arguments
while (( "$#" ));
do
	case "$1" in
        -h|--help)
            showUsage
            shift # past argument
            exit 0
            ;;
        --) # end argument parsing
            shift
            break
            ;;
        -*|--*=) # unsupported flags
            showUsage
            echo -e "${RED}[ERROR] Unsupported flag $1${NC}"
            echo -e ""
            exit 1
            ;;
        *) # preserve positional arguments
            PROJECT_NAME="$1"
            shift
            ;;
	esac
done

if [ "${PROJECT_NAME}" == "" ]; then
    showUsage
    echo -e "${RED}[ERROR]${NC} Missing project name!"
    echo ""
    exit 0
fi

echo "[INFO] Stopping ${GREEN}${PROJECT_NAME}${NC} docker instance"
docker-compose --project-name ${PROJECT_NAME} down

echo "[INFO] Done !"
echo ""
    



